openapi: 3.0.1
info:
  title: Sentiment Analysis Plugin
  description: A plugin that allows performing sentiment analysis on provided text using Google Natural Language API.
  version: 'v1'
servers:
  - url: http://localhost:8080/
paths:
  /analyze:
    post:
      operationId: analyzeSentiment
      summary: Analyze the sentiment of a text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
components:
  schemas:
    AnalyzeRequest:
      type: object
      properties:
        text:
          type: string
          description: The text to analyze.
    AnalyzeResponse:
      type: object
      properties:
        documentSentiment:
          type: object
          properties:
            magnitude:
              type: number
            score:
              type: number
          description: The overall sentiment of the input text.
        sentences:
          type: array
          items:
            type: object
            properties:
              text:
                type: object
                properties:
                  content:
                    type: string
                  beginOffset:
                    type: integer
              sentiment:
                type: object
                properties:
                  magnitude:
                    type: number
                  score:
                    type: number
          description: The sentiment for all the sentences in the input text.
